name: Test Nsolid Action

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  nsolid-version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        nsolid-version: [5]
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nsolid and check latest
        uses: ./
        with:
          nsolid-version: ${{ matrix.nsolid-version }}
      - name: Verify Nsolid
        run: | 
            nsolid -vv
            node -vv
      - name: Verify Node version
        run: |
            nsolid -v
            node -v

  nsolid-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Nsolid from dist
        uses: ./

      - name: Verify Nsolid
        run: | 
            nsolid -vv
            node -vv
      - name: Verify Node version
        run: |
            nsolid -v
            node -v